version: 2

jobs:
  test:
    docker:
      - image: cypress/base:latest
    working_directory: ~/test-github-app
    steps:
      - checkout
      - run:
          name: Install Dependencies and Required Libraries
          command: |
            npm install
            apt-get update && apt-get install -y \
              libgtk2.0-0 \
              libgtk-3-0 \
              libgbm-dev \
              libnotify-dev \
              libnss3 \
              libxss1 \
              libasound2 \
              libxtst6 \
              xauth \
              xvfb
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: cypress-image-diff-screenshots
      - store_artifacts:
          path: cypress-image-diff-html-report
      - persist_to_workspace:
          root: .
          paths:
            - cypress-image-diff-screenshots
            - cypress-image-diff-html-report
      - run:
          name: Waiting for upload
          command: echo "Uploaded successfully"

workflows:
  version: 2
  test-circle:
    jobs:
      - test
