version: 2

jobs:
  visual-test:
    docker:
      - image: cypress/base:latest
    # your actual working directory
    working_directory: ~/test-github-app
    steps:
      - checkout
      - run:
          name: Install Dependencies and Required Libraries
          command: |
            npm install
            apt-get update && apt-get install -y \
              libgtk2.0-0 \
              libgtk-3-0 \
              libgbm-dev \
              libnotify-dev \
              libnss3 \
              libxss1 \
              libasound2 \
              libxtst6 \
              xauth \
              xvfb
      - run:
          name: Run Tests
          # replace with your actual test command
          command: npm run test
      - store_artifacts:
          # replace with your actual folder path if you have a custom one
          path: cypress-image-diff-screenshots
      - store_artifacts:
          # replace with your actual folder path if you have a custom one
          path: cypress-image-diff-html-report
workflows:
  version: 2
  cypress-image-diff:
    jobs:
      # job name should NOT be modified
      - visual-test
