version: 2.1

orbs:
  github-status: samsalisbury/github-status@0.0.2

jobs:
  cypressImageDiff:
    docker:
      - image: cypress/base:latest
    working_directory: ~/test-github-app
    steps:
      - checkout
      - run:
          name: Install Dependencies and Required Libraries
          command: |
            npm install
            apt-get update && apt-get install -y \
              libgtk2.0-0 \
              libgtk-3-0 \
              libgbm-dev \
              libnotify-dev \
              libnss3 \
              libxss1 \
              libasound2 \
              libxtst6 \
              xauth \
              xvfb \
              curl
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: cypress-image-diff-screenshots
      - store_artifacts:
          path: cypress-image-diff-html-report
      - run:
          name: Update Cicle CI target url
          command: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_STATUS_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$GITHUB_USER/statuses/$CIRCLE_SHA1 \
              -d '{"state":"success","target_url":"$CIRCLE_BUILD_URL?jobId=$CIRCLE_WORKFLOW_JOB_ID","description":"The build succeeded!","context":"continuous-integration/jenkins"}'
workflows:
  version: 2
  test-circle:
    jobs:
      - cypressImageDiff
