version: 2.1

orbs:
  github-status: samsalisbury/github-status@0.0.2

jobs:
  cypressImageDiff:
    docker:
      - image: cypress/base:latest
    working_directory: ~/test-github-app
    steps:
      - checkout

      - run:
          name: Install Dependencies and Required Libraries
          command: |
            npm install
            apt-get update && apt-get install -y \
              libgtk2.0-0 \
              libgtk-3-0 \
              libgbm-dev \
              libnotify-dev \
              libnss3 \
              libxss1 \
              libasound2 \
              libxtst6 \
              xauth \
              xvfb \
              curl
      - github-status/post_status:
          state: pending
          description: "Pending description"
          context: "ci/circleci"
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: cypress-image-diff-screenshots
      - store_artifacts:
          path: cypress-image-diff-html-report

workflows:
  version: 2
  test-circle:
    jobs:
      - cypressImageDiff
