version: 2.1

jobs:
  cypressImageDiff:
    docker:
      - image: cypress/base:latest
    working_directory: ~/test-github-app
    steps:
      - checkout
      - run:
          name: Install Dependencies and Required Libraries
          command: |
            npm install
            apt-get update && apt-get install -y \
              libgtk2.0-0 \
              libgtk-3-0 \
              libgbm-dev \
              libnotify-dev \
              libnss3 \
              libxss1 \
              libasound2 \
              libxtst6 \
              xauth \
              xvfb \
              curl
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: cypress-image-diff-screenshots
      - store_artifacts:
          path: cypress-image-diff-html-report

      - run:
          name: Set Success Status
          when: on_success
          command: |
            set -euo pipefail
            API=https://api.github.com
            USER=$(echo $CIRCLE_REPOSITORY_URL | cut -d'/' -f4)
            REPO=$(echo $CIRCLE_REPOSITORY_URL | cut -d'/' -f5)
            SHA=$CIRCLE_SHA1
            CONTEXT="ci/circleci"
            DESCRIPTION="Custom: Success"
            URL=$API/repos/$USER/$REPO/statuses/$SHA
            BODY='
              {
                "state": "success",
                "target_url": "'"$CIRCLE_BUILD_URL"'",
                "description": "'"$DESCRIPTION"'",
                "context": "'"$CONTEXT"'"
              }
            '
            echo $BODY | curl -u $GITHUB_STATUS_TOKEN:x-oauth-basic -XPOST -d@- $URL

workflows:
  version: 2
  test-circle:
    jobs:
      - cypressImageDiff
